<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Penduduk;
use Illuminate\Support\Facades\DB;

class PendudukController extends Controller
{
    public function __construct()
    {
        $this->penduduk = new Penduduk();
    }
    //
    public function createForm()
    {
        return view('penduduk/create');
    }

    public function editForm($id)
    {
//        error_log($penduduk)
        $data = $this->penduduk->find($id);
;
        return view('penduduk/edit', ['penduduk' => $data]);
    }
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
//            'email' => 'required|email',
//            'phone' => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10',
//            'subject'=>'required',
//            'message' => 'required',
            'no_kk' => 'required|max:16|min:16',
//            'validasi' => 'required',
            'nik' => 'required|max:16|min:16',
//            'hub_keluarga' => 'required',
//            'status_kawin' => 'required',
//            'jenis_kelamin' => 'required',
//            'agama' => 'required',
//            'tempat_lahir' => 'required',
//            'tgl_lahir' => 'required',
//            'rt' => 'required',
//            'rw' => 'required',
//            'dusun' => 'required',
        ]);

//            'tempat_lahir', 'tgl_lahir', 'umur', 'hub_keluarga',
//            'status_kawin', 'pendidikan', 'jenis_kelamin', 'agama', 'pekerjaan', 'nama_ayah', 'nama_ibu',
//            'status_pendidikan', 'alamat', 'tgl_nikah', 'no_buku_nikah', 'kua', 'akte_lahir', 'tgl_kematian',
//            'pukul_kematian', 'ket_kematian' , 'no_bpjs', 'jabatan', 'telepon', 'no_ijazah', 'nik_ayah', 'nik_ibu',
//            'tgl_cerai', 'no_akta_cerai', 'gol_darah', 'penyandang_cacat',

        //  Store data in database
        Penduduk::create($request->all());

//        return back()->with('success', 'Penduduk berhasil ditambahkan');
        return redirect()->route('list-penduduk.show')->with('success', 'Penduduk berhasil ditambahkan');
    }

    public function show_data(Request $request)
    {

        $penduduk=Penduduk::when($request->has("q"),function($q)use($request){
            return $q->where("nama","like","%".$request->get("q")."%");
        })->paginate(5);

//        $penduduk = Penduduk::all();
        $items = $request->items ?? 100;      // get the pagination number or a default
//        $penduduk = DB::table('penduduks')->paginate($items);

//        return parent::show($location, $name); // TODO: Change the autogenerated stub
//        return view('list-penduduk', ['penduduks' => $penduduk]);
        return view('list-penduduk', ['penduduks' => $penduduk, 'items' => $items]);
//            ->withClub($club)
//            ->withMembers($members)
//            ->withItems($items);
//        return view('club.' . config('app.locale') . '.index')
    }

}
