<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Penduduk;

class PendudukController extends Controller
{
    //
    public function createForm(Request $request)
    {
        return view('form-penduduk');
    }
    public function store(Request $request)
    {
        error_log($request);

        $this->validate($request, [
//            'name' => 'required',
//            'email' => 'required|email',
//            'phone' => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10',
//            'subject'=>'required',
//            'message' => 'required',
            'no_kk' => 'required|max:16',
//            'validasi' => 'required',
            'nik' => 'required|max:16',
            'nama' => 'required',
        ]);

//            'tempat_lahir', 'tgl_lahir', 'umur', 'hub_keluarga',
//            'status_kawin', 'pendidikan', 'jenis_kelamin', 'agama', 'pekerjaan', 'nama_ayah', 'nama_ibu',
//            'status_pendidikan', 'alamat', 'tgl_nikah', 'no_buku_nikah', 'kua', 'akte_lahir', 'tgl_kematian',
//            'pukul_kematian', 'ket_kematian' , 'no_bpjs', 'jabatan', 'telepon', 'no_ijazah', 'nik_ayah', 'nik_ibu',
//            'tgl_cerai', 'no_akta_cerai', 'gol_darah', 'penyandang_cacat',

        //  Store data in database
        Penduduk::create($request->all());

        return back()->with('success', 'Penduduk berhasil ditambahkan');
//        return redirect()->view('dashboard')->with('success', 'Penduduk berhasil ditambahkan');
    }

    public function show_data()
    {
        $penduduk = Penduduk::all();
//        return parent::show($location, $name); // TODO: Change the autogenerated stub
        return view('list-penduduk', [
            'penduduk' => $penduduk
        ]);
    }
}
